### ISSUE TITLE
v2.7 breaks XP compatibility

### ISSUE THREAD

**Issue by vogonsorg** [ccomrade/c1-launcher#16]
As of v2.7 the following is received on execution, it works fine on Vista. v2.6 still works fine on XP.

---------------------------
Crysis.exe - Unable To Locate Component
---------------------------
This application has failed to start because d3d10.dll was not found. Re-installing the application may fix this problem. 
---------------------------
OK   
---------------------------

**Comment by vogonsorg** [comment]
Possibly the following commit but I haven't tried reverting it:
https://github.com/ccomrade/c1-launcher/commit/f2059394e399e0da01aa314bebb37bb86e4971f0

**Comment by ccomrade** [comment]
Yes, it's already fixed in the master branch, but not released yet. The fixed version will be released soon. I'm still working on the new crash logger. Anyway, thanks for the report. It seems WinXP is still alive. :slightly_smiling_face:

**Comment by ccomrade** [comment]
Fixed in v3
