### ISSUE TITLE
v2.7 problem with overlay show things?

### ISSUE THREAD

**Issue by Lahrenheit** [ccomrade/c1-launcher#18]
Hello, idk if it is a bug but i post it; overlay works but don't work when I try open a new browser tab, seems load but not show anything, same with friends tab, only gray rectangle.
Thanks!

**Comment by ccomrade** [comment]
Hello, do you mean Steam overlay?

**Comment by Lahrenheit** [comment]
in-game overlay (shift+tab)

**Comment by ccomrade** [comment]
Have you tried running the game in DX9 mode?

**Comment by Lahrenheit** [comment]
It works, btw it doesn't work with directx10
I just added -dx9 in the steam parameters of the launcher

Thanks!
