### ISSUE TITLE
Failed to load CryRenderD3D10.dll

### ISSUE THREAD

**Issue by josdebruijn** [ccomrade/c1-launcher#26]
After I copy the c1 files to my steam folder. I get the following error when trying to open the game:
Failed to load CryRenderD3D10.dll
Error 126: The specified module could not be found.

That file is present on both my Bin32 and Bin64 folders.

**Comment by ccomrade** [comment]
Windows error reporting mechanisms are not great. This probably means that some of CryRenderD3D10.dll dependencies could not be loaded. Maybe DirectX libraries are missing. Steam should install all necessary libraries before first launch of the game, but you can also download DirectX libraries here:

https://www.microsoft.com/en-us/download/details.aspx?id=35

By the way, did you try DX9 mode by running Crysis.exe with `-dx9` parameter?

**Comment by josdebruijn** [comment]
Thanks, updating the DirectX libraries and setting dx9 mode resolved the issue for me.

**Comment by ccomrade** [comment]
DX10 mode should work as well with installed DirectX libraries. Unless you're on WinXP. However, there are no real benefits of DX10 mode anyway. Although it's worth mentioning that vanilla game doesn't allow using Very High settings in DX9 mode.

**Comment by vlad54rus** [comment]
DX10 is useful if you want to use Nvidia's Transparency Supersampling as it doesn't seem to do anything in DX9.  CryTek's EdgeAA can't deal with all this foliage shimmering well.
It also gives me a slightly higher framerate.
