### ISSUE TITLE
/LARGEADDRESSAWARE flag needs to be added

### ISSUE THREAD

**Issue by vlad54rus** [ccomrade/c1-launcher#5]
To allow 32-bit c1-launcher allocate all 4 Gigs of memory instead of regular limit of 2 Gigs and avoid crashing during prolonged gameplay. Original Crysis.exe has this flag set.
I've tested it, replaying the Reckoning level with 32-bit c1-launcher with and without LAA flag set (can be simply set with PE Tools). Without it, the game crashed with memory allocation error after ~hour of gameplay when process memory usage hit ~1.8 GB.

**Comment by ccomrade** [comment]
Nice catch. Fixed in 2.5. Thanks.
