### ISSUE TITLE
VirusTotal behavior question

### ISSUE THREAD

**Issue by Toquita3D** [ccomrade/c1-launcher#52]
Hi there!
First of all, let me thank you for creating this launcher. It's not that common to find such passionate people that fully create a new launcher with fixes, for a 17 years old game.

I'm always a bit suspicious to try any new executables, so I decided to push your release to VirusTotal. You can see the results [here](https://www.virustotal.com/gui/file/24fdd6e414e1e3b3f4b1a3af9f7967b19d6127d771df518383814dbe15b1eb0b).

Can you help me with a couple questions?

- the launcher creates the process `C:\Windows\System32\7za.exe` with the arguments `x -pinfected`. I'm particularly curious about the -pinfected argument because AFAIK "-p" is for the decryption password and "infected" is usually the password for malicious files.
The file extracted is C:\Users\[user]\AppData\Local\Temp\q4x40ebu.tmp, but I don't have access to that file as it's in a virtual machine I can't access.

- then it forcefully starts Conhost.exe in a hidden PowerShell (V1) window:
`C:\Windows\System32\conhost.exe C:\Windows\system32\conhost.exe 0xffffffff -ForceV1`

You can find some answers [here ](https://www.linkedin.com/posts/ryanjchapman_dfir-blueteam-cybersecurity-activity-7057458353047801857-_BVK/)on why a program might wanna do this.

Could this be caused by something else? Like the compiler, or the .exe builder.

Thanks

**Comment by jlallas384** [comment]
The 7za thing is the sandbox extracting the file to be analyzed. It's not the launcher that created the process.

**Comment by Toquita3D** [comment]
Hey guys,
Thank you for responding so quickly.

The reason I'm hesitant to dismiss this as a sandbox behavior is because no other game executable (or any executable at all) I tried does this, and _this includes the original Crysis binaries_.

The "Processes Created" part isn't part of the sandbox and only displays what the executable itself does.

As an example, [here's Assetto Corsa's game executable](https://i.imgur.com/L3qYDtA.png).
And [here's CS2's executable](https://i.imgur.com/ckcZZaN.png).

**Comment by ccomrade** [comment]
Hmmmm does the suspicious activity disappear if you upload directly one of the executables instead of the whole zip?

**Comment by Toquita3D** [comment]
You're right, [it does](https://www.virustotal.com/gui/file/04bdaa180aeae4bbce284e0f95acda4c6ee3414f05eff0925f25c3856ac15822/behavior) :)

So my guess is that _this was in fact_ a sandbox thing. When I upload it as a compressed archive, the sandbox decompresses it using 7z, and the "infected" password is used _exactly_  for the reason that it's a common password for infected archives.

So the suspicious behavior doesn't happen if I upload the executable directly.

My apologies if I made any hearts race today! hehehe. And thank you for the patience and quick response times.
I'm gonna start using the launcher from now on ;-)

**Comment by Toquita3D** [comment]
Just wanted to say that your launcher is amazing! Is there any way I can donate to the project? It's not much (converting from BRL to USD) but it's a small action of appreciation.

**Comment by ccomrade** [comment]
Thank you, i appreciate, but money isn't a problem. Time is. :slightly_smiling_face:
