### ISSUE TITLE
Intro

### ISSUE THREAD

**Issue by MOOOOs** [ccomrade/c1-launcher#9]
How do i get back my intro when i lauch the game?

**Comment by ccomrade** [comment]
You probably removed all files from `Game/Localized/Video/`. There's no need to remove anything from there. This launcher automatically skips all startup video ads. Or you want those ads back? There's no way to show the ads with this launcher. However, you can play them manually if you really want. I've tried to play some of them with `mpv` and it works just fine.

**Comment by MOOOOs** [comment]
No i only applied these files its game from steam

**Comment by MOOOOs** [comment]
i need them to play on startup how do i do that

**Comment by ccomrade** [comment]
So you want those startup video ads? But why? I think nobody really likes these. Some of them even can't be skipped (EA and ESRB).

**Comment by MOOOOs** [comment]
yeah i want them how do i bring them back

**Comment by ccomrade** [comment]
There's no way, but you can do the following:
- get the source code
- remove line 1263 in `Code/Launcher/Patch.cpp`:
```cpp
DisableIntros(libs);
```
- compile your own EXE that doesn't skip those ads

**Comment by ccomrade** [comment]
You can now use `-splash` command line parameter to restore startup intros.
